# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_param', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('gps_point', models.CharField(default=b'RA', max_length=200)),
                ('time_param', models.IntegerField(default=0)),
                ('mobile', models.CharField(max_length=9)),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('online', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=200)),
                ('time_param', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop1.Category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop1.Producer')),
            ],
        ),
    ]
