# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0002_customer_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop1.Customer'),
        ),
    ]
