# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'producers_img')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop1.Producer')),
            ],
        ),
    ]
