# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0005_producerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerdetail',
            name='picture',
            field=models.ImageField(height_field=b'243', upload_to=b'producers_img', width_field=b'195'),
        ),
    ]
