# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0008_auto_20170217_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerdetail',
            name='picture',
            field=models.ImageField(upload_to=b'producers_img'),
        ),
    ]
