# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0009_auto_20170217_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerdetail',
            name='producer',
        ),
        migrations.AddField(
            model_name='producer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'img/producers'),
        ),
        migrations.DeleteModel(
            name='ProducerDetail',
        ),
    ]
