# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0011_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.TextField()),
            ],
        ),
    ]
